apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: evaluationengine-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: evaluation
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluationengine
  namespace: evaluation
  labels:
    app: evaluationengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluationengine
  template:
    metadata:
      labels:
        app: evaluationengine
    spec:
      nodeSelector:
        role: master
      containers:
      - name: evaluationengine
        image: registry.local/evaluation-engine:0.4.2
        ports:
        - containerPort: 8080
        env:
        - name: "EVALUATION_ENGINE_HOST"
          valueFrom:
            configMapKeyRef:
              name: global-vars
              key: evaluation_service_host
        - name: "LOGGING_LEVEL_COM_GITHUB_KUDEPLATFORM"
          value: "debug"
        - name: "USE_WATCH_TO_DETECT_COMPLETION"
          value: "true"
        resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 3
---
apiVersion: v1
kind: Service
metadata:
  name: evaluationengine
  namespace: evaluation
spec:
  selector:
    app: evaluationengine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
