apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluationengine
  labels:
    app: evaluationengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluationengine
  template:
    metadata:
      labels:
        app: evaluationengine
    spec:
      containers:
      - name: evaluationengine
        image: registry.local/evaluationengine:0.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: evaluationengine
spec:
  selector:
    app: evaluationengine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
