kind: Service
apiVersion: v1
metadata:
  name: evaluationengine
  namespace: evaluation
spec:
  clusterIP: None
---
kind: Endpoints
apiVersion: v1
metadata:
  name: evaluationengine
  namespace: evaluation
subsets:
  - addresses:
      - ip: 192.168.2.20
    ports:
      - port: 8080

