- name: Install Loki
  become: true
  hosts: bootstrapMaster
  tasks:
  - name: Uninstall Loki
    shell: helm uninstall --kubeconfig /etc/rancher/k3s/k3s.yaml loki
    ignore_errors: yes
  - name: Uninstall Grafana
    shell: helm uninstall --kubeconfig /etc/rancher/k3s/k3s.yaml grafana
    ignore_errors: yes
  - name: Copy loki configuration file
    copy:
      src: ./loki/values.yaml
      dest: /tmp/loki-values.yaml
  - name: Copy grafana configuration file
    copy:
      src: ./grafana/values.yaml
      dest: /tmp/grafana-values.yaml
  - name: Copy grafana dashboards
    copy:
      src: ./grafana/grafana-dashboard-configmap.yaml
      dest: /tmp/grafana-dashboard-configmap.yaml
  - name: Install configmap
    shell: kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml apply -f /tmp/grafana-dashboard-configmap.yaml
  - name: Install Loki
    shell: | 
      helm repo add grafana https://grafana.github.io/helm-charts
      helm repo update
      helm install --kubeconfig /etc/rancher/k3s/k3s.yaml --values /tmp/loki-values.yaml loki grafana/loki
  - name: Install grafana
    shell: | 
      helm install --kubeconfig /etc/rancher/k3s/k3s.yaml --values /tmp/grafana-values.yaml grafana grafana/grafana 
  - name: Remove loki configuration file
    shell: rm -f /tmp/loki-values.yaml
  - name: Remove grafana configuration files
    shell: |
      rm -rf /tmp/grafana-dashboard-configmap.yaml
      rm -rf /tmp/grafana-values.yaml
    