- name: Label master node
  become: true
  hosts: bootstrapMaster
  gather_facts: true
  tasks:
  - name: Ping host
    ansible.builtin.ping:
  - name: Label bootstrapMaster
    shell: kubectl label node {{ ansible_hostname }} role=master
  - name: Label worker nodes
    shell: kubectl get nodes -l '!role' -o 'jsonpath={.items[*].metadata.name}' | xargs -n1 -I% kubectl label node % role=worker
