- name: Remove all containers
  become: true
  hosts: pies
  tasks:
  - name: Ping hosts
    ansible.builtin.ping:
  - name: Remove all containers
    shell: sudo k3s ctr image list -q | xargs sudo k3s ctr image del
    ignore_errors: yes

- name: Uninstall k3s bootstrap server
  become: true
  hosts: bootstrapMaster
  tasks:
  - name: Ping host
    ansible.builtin.ping:
  - name: Uninstall k3s bootstrap server
    shell: /usr/local/bin/k3s-uninstall.sh
    ignore_errors: yes
  - name: delete /etc/rancher dir
    ansible.builtin.file:
      state: absent
      path: /etc/rancher

- name: Uninstall k3s workers
  become: true
  hosts: workers
  tasks:
  - name: Ping hosts
    ansible.builtin.ping:
  - name: Uninstall k3s workers
    shell: /usr/local/bin/k3s-agent-uninstall.sh
    ignore_errors: yes
  - name: delete /etc/rancher dir
    ansible.builtin.file:
      state: absent
      path: /etc/rancher


- name: Uninstall Docker
  become: true
  hosts: pies
  tasks:
  - name: Ping hosts
    ansible.builtin.ping:
  - name: Uninstall docker
    ansible.builtin.apt:
      state: absent
      pkg:
      - docker.io