apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: data-manager
  namespace: evaluation
  labels:
    k8s-app: data-manager
spec:
  selector:
    matchLabels:
      name: data-manager
  template:
    metadata:
      labels:
        name: data-manager
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: data-manager
        image: registry.local/data-manager:0.0.2
        ports:
          - containerPort: 8090
            protocol: TCP
        env:
          - name: "SERVER_PORT"
            value: "8090"
          - name: EVALUATION_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: global-vars
                key: evaluation_service_host
          - name: "EVALUATION_SERVICE_PORT"
            value: "8080"
          - name: "DATASET_DIR"
            value: "/data"
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 25Mi
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /data