apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: evaluation
  labels:
    k8s-app: log-collector
spec:
  selector:
    matchLabels:
      name: log-collector
  template:
    metadata:
      labels:
        name: log-collector
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: log-collector
        image: registry.local/log-collector:0.0.3
        ports:
          - containerPort: 3000
            hostPort: 31179
            protocol: TCP
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 25Mi
        volumeMounts:
        - name: varlog
          mountPath: /home/logs
      volumes:
      - name: varlog
        hostPath:
          path: /var/log