apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-analyzer
  namespace: evaluation
  labels:
    k8s-app: log-analyzer
spec:
  selector:
    matchLabels:
      name: log-analyzer
  template:
    metadata:
      labels:
        name: log-analyzer
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: log-analyzer
        image: registry.local/log-analyzer:0.0.9
        ports:
          - containerPort: 8089
            protocol: TCP
        env:
          - name: "SERVER_PORT"
            value: "8089"
          - name: "EVALUATION_SERVICE_HOST"
            value: "192.168.178.25"
          - name: "EVALUATION_SERVICE_PORT"
            value: "8080"
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 25Mi
        volumeMounts:
        - name: varlog
          mountPath: /home/logs
      volumes:
      - name: varlog
        hostPath:
          path: /var/log