{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\"} | json message=\"log\", time=\"time\", kubernetesPodName=\"kubernetes.pod_name\", evaluationId=`kubernetes.labels[\"batch.kubernetes.io/job-name\"]`, index=`kubernetes.labels[\"batch.kubernetes.io/job-completion-index\"]`"
    }
   ]
  }
 ]
}
{
 "title": "Test Image",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobName",
    "label": "Job Name",
    "query": "ddm-akka-fcb9185a-1262-47b5-a0a4-0e0741baf34c.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Network-Receive-Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{pod=~\"$jobName\"}"
    }
   ]
  },
  {
   "title": "Network-Transmit-Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{pod=~\"$jobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$jobName\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$jobName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}