sidecar:
  dashboards:
    enabled: true
adminUser: admin
adminPassword: admin
service:
  enabled: true
  type: NodePort
  nodePort: 32300
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      uid: "P8E80F9AEF21F6940"
      url: http://loki:3100
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: '1'
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboardsConfigMaps:
  default: "grafana-dashboards"
nodeSelector:
  role: master